/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { VCalendar } from 'react-native-events-week-calendar';

export default class App extends Component<{}> {
  constructor(props) {
    super(props);
    this.state = {
      data: [
        {
          Title: "No Name",
          events: [
            {
              start: '2020-09-07 08:00:00',
              end: '2020-09-07 08:45:00',
              title: 'Dr. Mariana Lisa',
              summary: '3412 Piedmont Rd NE, GA 3032',
              color: 'green',
            },
            {
              start: '2020-09-07 08:30:00',
              end: '2020-09-07 10:30:00',
              title: 'Dr. Mariana Joseph',
              summary: '3412 Piedmont Rd NE, GA 3032',
            },
            {
              start: '2020-09-07 11:15:00',
              end: '2020-09-07 12:30:00',
              title: 'Dr. Mariana Vinh',
              summary: '3412 Piedmont Rd NE, GA 3032',
            },]
        },
        {
          Title: "Vinh Tran",
          events: [
            {
              start: '2020-09-07 09:00:00',
              end: '2020-09-07 09:45:00',
              title: 'Dr. Mariana Lisa',
              summary: '3412 Piedmont Rd NE, GA 3032',
              color: 'green',
            },
            {
              start: '2020-09-07 09:15:00',
              end: '2020-09-07 10:30:00',
              title: 'Dr. Mariana Joseph',
              summary: '3412 Piedmont Rd NE, GA 3032',
            },
            {
              start: '2020-09-07 09:45:00',
              end: '2020-09-07 12:30:00',
              title: 'Dr. Mariana Vinh',
              summary: '3412 Piedmont Rd NE, GA 3032',
            },]
        },
        { Title: "Dat Nguyen" },
        { Title: "Tri Tran" },
        { Title: "Hung Vu" },

        { Title: "Tung Nguyen" },
        { Title: "Ước Phạm" },
        { Title: "Quang Bui" },
      ]
    }
  }
  onNewEvent = (item) => {
    console.log(item)
    const { index, Title, hours } = item
    const msg = `index=${index}, Title=${Title}, hours=${hours.from}-${hours.to}`
    alert(msg)
  }
  onClickEvent = (item) => {
    console.log(item)
    const msg = `${item.title}\n${item.summary}\n\n${item.start} - ${item.end}`
    alert(msg)
  }
  render() {
    const headers = this.state.data
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆VCalendar example☆</Text>
        <Text style={styles.instructions}>STATUS: loaded</Text>
        <Text style={styles.welcome}>☆☆☆</Text>
        <VCalendar
          onNewEvent={this.onNewEvent}
          onClickEvent={this.onClickEvent}
          columnHeaders={headers}
          title="My Title"
          hourStart={8}
          hourEnd={17}
          showHourStart={7}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
